draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30
  combo_w: 26
  combo_h: 22
  key_rx: 6
  key_ry: 6
  n_columns: 1
  separate_combo_diagrams: false
  svg_extra_style: |
    svg {
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 14px;
    }
    rect.held {
      fill: #ffc;
    }
parse_config:
  zmk_keycode_map: {}
  raw_binding_map:
    "&mmv MOVE_LEFT": {tap: "← Move"}
    "&mmv MOVE_DOWN": {tap: "↓ Move"}
    "&mmv MOVE_UP": {tap: "↑ Move"}
    "&mmv MOVE_RIGHT": {tap: "→ Move"}
    "&msc SCRL_LEFT": {tap: "← Scroll"}
    "&msc SCRL_DOWN": {tap: "↓ Scroll"}
    "&msc SCRL_UP": {tap: "↑ Scroll"}
    "&msc SCRL_RIGHT": {tap: "→ Scroll"}
    "&mkp LCLK": {tap: "L Click"}
    "&mkp RCLK": {tap: "R Click"}
    "&mkp MCLK": {tap: "M Click"}
    "&hyper": {tap: "Hyper"}
    "&mt LCTRL ESC": {tap: "Esc", hold: "Ctrl"}
  sticky_label: sticky
  toggle_label: toggle
  trans_legend:
    tap: "▽"
    type: trans
